### ISSUE TITLE
Template Inheritance

### ISSUE THREAD

**Issue by davidgovea** [pugjs/pug-loader#1]
Doesn't seem like this loader supports jade's `extends [name]` inheritance..
## one.jade

``` jade
doctype 5
html
    body
        <h1>Test</h1>
        block content
```
## two.jade

``` jade
extends one

block content
    p Hello!
```
## project.js

``` javascript
console.log( require('./two.jade')() );
```

Webpack complains that it can't find module two.jade.

What is the recommended approach here?

For now, I switched to a grunt task that compiles each template using `jade -c` & then lets webpack eat the precompiled templates.

**Comment by davidgovea** [comment]
Additionally, I should mention that I have tried `require`ing the `one.jade` template before `two.jade` in `project.js` - still no go.

**Comment by sokra** [comment]
It should support it now...

It is limited to `.jade` files and do not support generated jade by other loaders.

Additionally jade uses `fs.readFileSync` internally to load the extending file. This may results in a performance problem.

**Comment by davidgovea** [comment]
Thanks for the quick fix sokra!
