### ISSUE TITLE
Cannot find module 'pug'

### ISSUE THREAD

**Issue by mittalyashu** [pugjs/pug-loader#103]
Getting this error.

![image](https://user-images.githubusercontent.com/29014463/35474778-f2818e7a-03b8-11e8-895b-ce2447dbf517.png)

I was trying to use jade as a template in `HtmlWebpackPlugin`, but it's somehow not working.

**Comment by johanguse** [comment]
Same here...

**Comment by zigang93** [comment]
as error said, missing `pug` package

`npm i -D pug` 

Please install the `pug` before u start using `pug-loader`

**Comment by mittalyashu** [comment]
Do we also need to use pug (package) inside the webpack config file too?

**Comment by zigang93** [comment]
No.. no need.

**Comment by mittalyashu** [comment]
Okay. Thanks

**Comment by adebigare** [comment]
I know this issue is closed, but I wonder if a quick note could be added to the readme regarding adding the pug package?

**Comment by appsparkler** [comment]
This is what worked for me:

Install the `pug` npm module
`npm i -D pug`

**Comment by andyjessop** [comment]
I'm sure things like this seem obvious, but a little documentation on installation would be really helpful.

**Comment by nttrungqnh** [comment]
> This is what worked for me:
> 
> Install the `pug` npm module
> `npm i -D pug`

thanks you sloved my problem
