### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by omichelsen** [pugjs/pug-loader#107]
I am getting this error after upgrading to Webpack 4:

```
Module build failed: TypeError: Cannot read property 'pugLoader' of undefined
```

Is this something that's on the radar? :-)

**Comment by filipecosta01** [comment]
Same thing here...

were you able to solve it somehow @omichelsen?

**Comment by thedamfr** [comment]
+1

**Comment by kronos93** [comment]
Same thing here
Using the next packages:
```json
{
 "webpack": "^4.0.1",
 "pug-loader": "^2.3.0",
 "html-webpack-plugin": "github:webpack-contrib/html-webpack-plugin",
}
```
```bash
ERROR in ../node_modules/html-webpack-plugin/lib/loader.js!./src/index.pug
    Module build failed: TypeError: Cannot read property 'pugLoader' of undefined
        at Object.exports.getLoaderConfig (C:\Users\Dell\Desktop\wp-beta\node_modules\pug-loader\node_modules\loader-utils\index.js:124:37)
        at Object.module.exports (C:\Users\Dell\Desktop\wp-beta\node_modules\pug-loader\index.js:20:26)
```

**Comment by roman-vabishchevych** [comment]
+1

**Comment by dmitrijs-balcers** [comment]
+1

**Comment by jlopez994** [comment]
Okay I think I found a workaround.

First of all, it seems "pug-loader" is installed wrongly. I mean, if you check your dependency, you will see it is outdated (Last commit is not present). So be sure you have the last one.
Secondly, you have to add the key "query" in order to get it works, so the loader would be something like this:
```
{
  test: /.pug$/,
  use: {
    loader: 'pug-loader',
    query: {} // Can be empty
  }
}
```

**Comment by dackmin** [comment]
+1s don't help anyone. 
@sokra do you have write access to `pug-loader` npm package to make a release from `master` along with #101  ? Or do I have to harass everybody @pugjs ? 😄

**Comment by marco-carvalho** [comment]
it worked here using @esejuli94 workaround AND installing pug-loader tarball:
`npm i -D https://github.com/pugjs/pug-loader/tarball/master`

**Comment by JoshuaSebastianKim** [comment]
It seems that the issue comes from the "loader-utils@0.2.17" dependecy package.
The recent webpack update removed the "loaderContext.options" property which is used [here](https://github.com/webpack/loader-utils/blob/v0.2.17/index.js#L124).

**Comment by dackmin** [comment]
@TimothyGu do you have time to review this ?

**Comment by tomciklukas** [comment]
@JoshuaSebastianKim package.json lists loader-utils: ^1.1.0 but installs 0.2.17 from npm ... i don't get it :/

**Comment by zacfukuda** [comment]
`yarn add --dev webpack@3.11.0 webpack-dev-server@2.11.1`
I simply downgraded the version of two dependencies and solved the problem.

I’ve got the same issue and none of the solutions mentioned above worked for me.
The issue is, I believe, due to the latest version of Webpack and Webpack DevServer.

Before that, I used webpack@4.xx.xx and webpack-dev-server@3.xx.xx, probably just like you guys did. For this moment, I think we should wait Webpack team fixes the bug , and better off with the older versions. Hope this would be helpful for some of you.

(Similar issues are found with `ejs` related loaders as well. That’s why I tried Pug for the first time—although it didn’t work.)

**Comment by phiphou** [comment]
Using @marco-carvalho solution I get `Cannot read property 'doctype' of null`.

Any solution ?

**Comment by melgish** [comment]
@phiphou Just put in a pull request with a fix to allow zero config.  In the meantime specifying the loader with empty options should be a viable work-around.

{ loader: 'pug-loader', options: {} }

**Comment by marco-carvalho** [comment]
@phiphou do u have some repo that we can clone and see this error?

**Comment by vagusX** [comment]
how is it going now? I don't think this repo is deprecated? @TimothyGu

**Comment by dackmin** [comment]
former repo owners (@sokra or @TimothyGu) don't seem to have time to check this.
#101 already fixes everything, only needs to be merged & published to npm

**Comment by phiphou** [comment]
@marco-carvalho No, I will maybe made some this week. For now I decided not to use pug-loader anymore.

**Comment by zzois** [comment]
I just tried what @esejuli94 and @marco-carvalho proposed as a solution and can (contrary to @phiphou report), confirm that it seems to be working fine for me also. I agree with @dackmin that it would be really convenient if #101 could be merged and everything published to npm.

**Comment by zzois** [comment]
Just a note - (possibly empty) 'request' key can be exchanged with (possibly empty) 'option' key  (as suggested by @melgish) and this also works fine.

I'm rather new to Webpack, so this was new to me: https://webpack.js.org/guides/migrating/#what-are-options-

**Comment by phiphou** [comment]
I don't really know what I've done but it now works well.

**Comment by marco-carvalho** [comment]
@phiphou maybe some upgrade on devDependencies package-lock.json?

**Comment by phiphou** [comment]
Maybe....

**Comment by Disorrder** [comment]
Same issue, but I forked with #101 fix and it's fine. Looking forward to merge that

**Comment by bazineta** [comment]
Works great here with #101. Would be nice to see that merged and npm resynchronized; it's been out of sync for some time.

**Comment by theSoenke** [comment]
Does this repository still does has any maintainer? Maybe another @pugjs organization members can help get this merged and release a new version? For example @ForbesLindesay?

**Comment by toobull** [comment]
@marco-carvalho thx,it's useful
`npm i -D https://github.com/pugjs/pug-loader/tarball/master`

btw,loader need write like
`            {
                test : /\.pug$/,
                use: {
                    loader: 'pug-loader',
                    query: {}
                }
            }
`
and it's not ok
`            {
                test : /\.pug$/,
                loader: 'pug-loader'
            }
`

**Comment by Paveldub** [comment]
`test: /\.pug$/,
        loader: "pug-loader",
        options: {
          pretty: true
        }`

Guys tell me please about option? I have the same problem:

> - configuration.module.rules[5] has an unknown property 'option'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, resolve?, sideEffects?, query?, type?, resource?, resourceQuery?, compiler?, rules?, test?, use? }

**Comment by dackmin** [comment]
@ForbesLindesay did the job, `2.4.0` is out and working fine with `webpack@4`.
Thanks a lot !

**Comment by vladislav-zayets** [comment]
I used webpack 3 and I want to transfer the project to webpack 4.
How can I change this part of the code?
///////
plugins: [
            new webpack.optimize.CommonsChunkPlugin({
                name: 'vendor',
                minChunks: function (module) {
                    return module.context && module.context.indexOf('node_modules') !== -1;
                }
            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: 'manifest',
                minChunks: Infinity
            })
        ]
/////////
