### ISSUE TITLE
img(src="./local/image.png")

### ISSUE THREAD

**Issue by 11111000000** [pugjs/pug-loader#11]
image src not handled any way. I want to use file-loader with it (like in stylus-loader)

**Comment by sokra** [comment]
You can write it this way:

``` js
img(src=require("./local/image.png"))
```

**Comment by 11111000000** [comment]
thank you!

**Comment by 11111000000** [comment]
may be add this to documentation?

**Comment by diegoleme** [comment]
And in that case:

```
srcset="./local/image.png 1x, ./local/image@2x.png 2x, ./local/image@3x.png 3x"
```

?

**Comment by yawlhead91** [comment]
@diegoleme any luck getting the srcset

**Comment by Edwin160508** [comment]
Sorry but its not work why? 

doctype html
html
    head
        title= title
    body
        main
            header                
                +menu
                section
                    figure
                        img(src=require("./images/banner.jpg"))

**Comment by ffpetrovic** [comment]
Can I just write a static `src` for the image...? ( `<img src="/img/myimage.png"/>` ) Without the source file actually going through webpack?

**Comment by NassimBouyacoub** [comment]
try 
img(src="/images/YourImages.png")
without /public

**Comment by BassOfBass** [comment]
@diegoleme
@yawlhead91
```pug
img(
srcset=`${require("./local/image.png")} 1x,
${require("./local/image@2x.png")} 2x,
${require("./local/image@3x.png")} 3x`
)
```
Or add [another loader](https://github.com/Calvin-LL/webpack-image-srcset-loader) I guess.
