### ISSUE TITLE
Fails with absolute paths

### ISSUE THREAD

**Issue by iliakan** [pugjs/pug-loader#13]
As of now, `getFileContent` cannot process absolute paths like `include /base`.

In jade, `include /base` is resolved relative to `options.basedir`, see https://github.com/visionmedia/jade/blob/master/lib/parser.js#L466-L469. 

So it is actually taken from `options.basedir`, that we take as correct.

In `jade-loader`, it is converted to `.//base` in the first line of `getFileContent`:

```
  function getFileContent(context, request) {
        request = /^~/.test(request) ? request.substr(1) : "./" + request;
```

...and taken from the current folder, that's wrong.

**Comment by iliakan** [comment]
P.S. maybe `getFileContent` should try to use the native `jade.Parser#resolvePath` ?

**Comment by colelawrence** [comment]
Consider changing `root` option to `basedir`, which is what jade options calls it.
