### ISSUE TITLE
How can i treat jade-loader to return string instead of template function

### ISSUE THREAD

**Issue by lovedota** [pugjs/pug-loader#15]
Hi guys.
This loader is very good. But I really want to combine this with https://github.com/teux/ng-cache-loader but this loader only accept string, how can i config this to return string to use like this. Thanks !
`{test: /\.jade/, loader: "jade-loader!ng-cache?prefix=[dir]/[dir]"},`

**Comment by aikoven** [comment]
Use `jade-html-loader`.
https://github.com/bline/jade-html-loader

**Comment by m0ppers** [comment]
@lovedota just stumbled upon a similar problem.

Just pipe it through the apply loader :)

My webpack config:

```
        {test: /\.ngtemplate\.jade$/, loader: 'ngtemplate!apply!jade'},
```

**Comment by colelawrence** [comment]
@m0ppers nice suggestion, I'll add this one to my collection :-)

**Comment by lovedota** [comment]
@m0ppers  Thanks nice !

**Comment by pmowrer** [comment]
@m0ppers Really excellent solution! It should go on the README. Added a PR for that.
