### ISSUE TITLE
how about `include require('text.md')`  ?

### ISSUE THREAD

**Issue by 11111000000** [pugjs/pug-loader#16]
via webpack

**Comment by sokra** [comment]
you can du that, with the markdown-loader

**Comment by 11111000000** [comment]
No, that not works:

``` jade
include require('./some.md');
```

with img src this workin, but with includes - no

**Comment by 11111000000** [comment]
please reopen the issue

**Comment by sokra** [comment]
include is for jade files.

``` jade
!= require('./some.md');
```

Please use Stackoverflow for questions.
