### ISSUE TITLE
extends/include root handling (basedir)

### ISSUE THREAD

**Issue by Craga89** [pugjs/pug-loader#20]
Is there some specification as to how a leading `/` is handled in `extends` or `include` statements?

Currently it looks as if the `loaderUtils.urlToRequest` method resolves `/views/layout.jade` to `.//views/layout.jade`, rather than `views/layout.jade`

The latter would presumably correctly resolve using the `modulesDirectories` lookup sequence?

**Comment by Craga89** [comment]
Ah just found the `root` query option when reviewing the code. Might be helpful to list this on the `README.md`?

**Comment by ernsheong** [comment]
Wasn't clear that `include /foo` is used to access the stuff in `root` (got that from the 1st comment). That would be a good inclusion as well
