### ISSUE TITLE
npm 3 peerDependencies

### ISSUE THREAD

**Issue by chiplay** [pugjs/pug-loader#22]
`The peer dependency jade@^1.7.0 included from jade-loader will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.`

Not sure the best solution, but probably needs to be updated soon to work properly with npm 3.

**Comment by TimothyGu** [comment]
Nah, that's intended. Add the jade/pug dependency to your own `package.json` as I don't want to limit users to a specific version by bundling.
