### ISSUE TITLE
使用jade-loader报错，见截图，我直接用gulp-jade编译jade文件没有问题，可以编译成js

### ISSUE THREAD

**Issue by fengxinming** [pugjs/pug-loader#28]
![qq 20151120174302](https://cloud.githubusercontent.com/assets/6262382/11296610/22cee9aa-8fae-11e5-80c1-d1d25e1f8e3d.png)
![qq 20151120174310](https://cloud.githubusercontent.com/assets/6262382/11296621/2c91253e-8fae-11e5-9e39-fbafe0fc591d.png)

**Comment by colelawrence** [comment]
JavaScript code may not be in the Jade source file itself.

Use code blocks if you want the code to run when rendering. see reference: http://jade-lang.com/reference/code/

Use script pipe when script needs to be in the rendered page html. See reference **Block in a Tag**: http://jade-lang.com/reference/plain-text/

Hope I helped!

**Comment by xiaosi-ss** [comment]
妈个鸡 竟然看到了你

**Comment by TimothyGu** [comment]
@fengxinming, do you speak English, and can you provide a test case?

@dan0314, please be civil with your language.

**Comment by xiaosi-ss** [comment]
@TimothyGu  意外意外 看到他就想打QAQ
