### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by lamuertepeluda** [pugjs/pug-loader#35]
``` jade
img(src=require("./my/image.png"))
```

is fine but what about background-image:url(...) ?

``` jade
div(style='background-image:url(require("./my/image.png))')
```

does not seem to work :disappointed:

**Comment by colelawrence** [comment]
There is no way for Jade to parse that out of the string, does
div(style='background-image:url(#{require("./my/image.png")})')
work?

**Comment by lamuertepeluda** [comment]
Yes, this works! Thank you! :smiley: 

It may be a good idea to add this to the samples too...

**Comment by colelawrence** [comment]
Haha, great! You can submit a pull request to add this as a sample.

**Comment by lamuertepeluda** [comment]
Done :ok_hand:

**Comment by tneumueller** [comment]
For everyone reading this, using pug >= 2.0.0:
Note that the syntax has been changed, you now need to use
```
div(style='background-image:url(' + require("./my/image.png") + ')')
```
or
```
div(style=`background-image:url(${require("./my/image.png")})`)
```
See https://github.com/pugjs/pug-loader/pull/36

**Comment by Asadullah766** [comment]
hi everyone! background image did not upload  please solve this issur
 ![png1 (2)](https://user-images.githubusercontent.com/98309717/150746486-19519320-86e9-4910-b5d2-2d8fdb662503.png)

**Comment by Asadullah766** [comment]
`doctype html 
html 
 head
   style  
     include ../views/css/style.css

block content
  div#navbar.top
    ul
      li #[a(href="/home")  Home]
      li #[a(href="/services")  Services]
      li #[a(href="/about")  About]
      li #[a(href="/contact")  Contact]
  section#introSection 
      h3 Section for picture
      img(src="./static/bg.jpg")
  section#sponsorsSecton 
      h3 Section for sponsor
  section#footer 
      h3 our footer  `

**Comment by Faizan-Ahmad04** [comment]
> `doctype html html head style include ../views/css/style.css
> 
> block content div#navbar.top ul li #[a(href="/home") Home] li #[a(href="/services") Services] li #[a(href="/about") About] li #[a(href="/contact") Contact] section#introSection h3 Section for picture img(src="./static/bg.jpg") section#sponsorsSecton h3 Section for sponsor section#footer h3 our footer `

bro you need to add this code in your   indes.js    or main file 

app.use('/static', express.static('static'));  

so that you can use static files
