### ISSUE TITLE
Rename to pug

### ISSUE THREAD

**Issue by MikaAK** [pugjs/pug-loader#38]
With jade being renamed to pug, it seems appropriate the loader do such as well. Thoughts?

**Comment by bullwinkle** [comment]
there is a some package on npm named "pug-loader", but it isn`t for webpack... 
https://github.com/pugjs/pug-load 
So, gentlemen, what your thoughts?

**Comment by colelawrence** [comment]
pugjs-loader?

**Comment by vdh** [comment]
The best solution would be to migrate their NPM module to `pug-load`, so that this one can then make use of `pug-loader`.

**Comment by vdh** [comment]
Good news! The NPM module has been updated to be `pug-load`, and it looks like [`pug-loader` will be available for use after the next alpha of Pug](https://github.com/pugjs/pug-load/issues/5#issuecomment-216717775).

**Comment by phyllisstein** [comment]
Looks like the name's been made available as of the latest Pug alpha: https://github.com/pugjs/pug/blob/master/package.json#L27.

**Comment by TimothyGu** [comment]
Hi, I'm a member of @pugjs. If you guys would like to use `pug-loader`, I can provide @sokra (or another member of @webpack) with the necessary permissions to use that package name on npm.

**Comment by axe312ger** [comment]
@TimothyGu nice! Thanks. Can't wait to port to pug, this is the last issue that prevents me from doing it :)

**Comment by sokra** [comment]
hi @TimothyGu / @pugjs do you want to move/create the pug-loader on your organization? I have too many repos to maintain...

**Comment by TimothyGu** [comment]
@sokra, moved. I'll update this module to Pug 2.0.0 when I get the time.

**Comment by LandonSchropp** [comment]
@TimothyGu: I'm sure you're a pretty busy guy, but it would be great to see an update on this issue. I just spent a few minutes trying to figure out why my `pug-loader` install didn't work before I realized that the NPM module is named `jade-loader`. Also, it would be nice to see an update to Pug 2.0. Thanks!

**Comment by TimothyGu** [comment]
@LandonSchropp and others, I have just published `pug-loader@2.0.0`, which now depends on `pug@2.0.0-beta3` or newer.

I'm not real familiar with Webpack so if I mess something up feel free to create new tickets. For now I'll consider this issue finished.

**Comment by LandonSchropp** [comment]
Thanks!

**Comment by vdh** [comment]
@TimothyGu Thanks for the update! I gave it a try but I ran into an issue with `include`: #44
