### ISSUE TITLE
Self closed tags?

### ISSUE THREAD

**Issue by ghost** [pugjs/pug-loader#39]
Is there an option for this? I'd like `<img/>` and `<br/>` tags etc...

**Comment by NoNameProvided** [comment]
Hi @vuoriliikaluoma 

Jade automatically self close the self closing tags. From the official docs: 

> Tags such as img, meta, link and so on are automatically self-closing (unless you use the xml doctype). 

However if you want to close other tags the [documentation](http://jade-lang.com/reference/tags/) says you can self close them with appending a slash to the end of the tag. 

Example Jade: 

``` jade
foo/
foo(bar='baz')/
```

The compiled HTML will look like this: 

``` html
<foo/>
<foo bar="baz"/>
```

You should consider closing this issue as it's not related to the jade-loader itself.

**Comment by ghost** [comment]
Thanks alot!

**Comment by ghost** [comment]
Actually:

```
img/
img(src)/
```

turns into:

```
<img><img src>
```

So it's not working in jade-loader, the same code run directly through jade produces:

```
<img/><img src="src"/>
```

Note both the self-closed tags and the attribute.

**Comment by ghost** [comment]
Finally figured it out! I had to add `doctype=xml` to the jade-loader query string. Had to read through Jade's API documentation and jade-loader's code to find the option though.

**Comment by bnettles** [comment]
Today, I encountered the issue using Pug.
img(class="responsiveImage" src="http://imageurl" )
Did not close the image tag.

img(class="responsiveImage" src="http://imageurl" )/
Closes the image tag.

**Comment by kimmo-steleco** [comment]
@bnettles Unclosed `img` tags are correct in Pug with HTML `doctype`.
So / is required to force closing.
You could try another `doctype` if that fits you needs better.

See: https://pugjs.org/language/doctype.html


_Woops, was logged in to my work account on this browser, I am @vuoriliikaluoma._

**Comment by webdiscus** [comment]
Pug v3.0.2 generate `<img src="img.png">` or `<img src="img.png" />` depend on `doctype`.

Using `doctype html`:

```pug
doctype html
html
  head
    link(rel="stylesheet" href="styles.css")
  body
    img(src="img.png")
```

will be generated with `>` for self-closing tags:
```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <img src="img.png">
  </body>
</html>
```

Using `doctype html5`:

```pug
doctype html5
html
  head
    link(rel="stylesheet" href="styles.css")
  body
    img(src="img.png")
```

will be generated with ` />` for self-closing tags:
```html
<!DOCTYPE html5>
<html>
  <head>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <img src="img.png" />
  </body>
</html>
```

P.S. It's recommended to use `doctype html`.

**Comment by eroffa** [comment]
**If use gulp builder**

```js
import pug from 'gulp-pug'

... some code
.pipe(
      pug({
        doctype: 'html',    // this setting gives the result
        ... other settings
     })
)
... some code
```
