### ISSUE TITLE
broken include inside EACH block

### ISSUE THREAD

**Issue by altano** [pugjs/pug-loader#4]
Hey there,

It looks like after 0.6.0, non-inlined includes can have the wrong context if the include is in an 'each' block.  For example, this jade:

``` jade
      each highlight in highlights
        li
          include highlight
```

Expanded to:

``` javascript
        for (var $index = 0, $$l = $$obj.length; $index < $$l; $index++) {
          var highlight = $$obj[$index];
          buf.push("<li>" + (null == (jade_interp = __webpack_require__(81).call(this, locals)) ? "" : jade_interp) + "</li>");
```

But the include is being called with "locals" only and doesn't have the 'highlight' variable in scope anymore.  The documentation for jade doesn't say what the exact behavior of the include is, but there are a lot of snippets on the internet that imply the include will have the full scope of the parent including the variable you are looping over.  And that's how I was using it.

I'm happy to change my code if rather than fixing this you can think of another way of getting proper partial support with jade-loader.

Thanks!

**Comment by sokra** [comment]
I've updated the jade dependency, so could you please check whether this is caused by a jade change or is a bug in the loader.

**Comment by altano** [comment]
It looks like you didn't push the change because the package.json on github hasn't been touched since March 11 and remains 1.2.x.

**Comment by altano** [comment]
(unless you meant you updated the dependency in 0.6.1, in which case I can confirm the issue I'm describing is in 0.6.1, the latest version)

**Comment by TimothyGu** [comment]
That's a Jade/Pug issue, not a pug-loader one.
