### ISSUE TITLE
"jade-loader" is called continuous 2 times

### ISSUE THREAD

**Issue by fengxinming** [pugjs/pug-loader#40]
When the jade template inside the "include" keyword, "jade-loader" module is called 2 times; I hide 171 lines of code, "jade-loader" module to load the normal jade template. You can test according to the following steps:
1、git clone https://github.com/fengxinming/koa-demo
2、npm install
3、npm run dev  or  npm run build

**Comment by TimothyGu** [comment]
Pug operates synchronously, but Webpack operates asynchronously. This is a hack necessary for includes in pug-loader to function at all.

Also, it's not the entire loader that's called twice, but only `run()`.

What's bad about this design?
