### ISSUE TITLE
Requiring CSS modules

### ISSUE THREAD

**Issue by michaek** [pugjs/pug-loader#42]
When requiring CSS modules (ex: `- styles = require('!css?modules!./styles.css')`), it seems that what's returned to Jade/Pug is the output CSS string, not the  object with original classname keys. Is there a way to ensure that the module map is returned to jade?

**Comment by TimothyGu** [comment]
Can you make a minimal example of this issue (preferably in a GitHub repo) and show the output file?

**Comment by vlazh** [comment]
You can access to classes through styles.locals:
`styles.locals.classname`
Or use css-loader/locals and then you can use:
`styles.classname`

**Comment by michaek** [comment]
At long last, I've made the test case for this, and what @vlazh says is exactly correct. Using `css-loader/locals` is even mentioned in the css-loader README regarding prerendering. Thanks for the pointer!
