### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by thedanheller** [pugjs/pug-loader#45]
I'm new to webpack and it would be great if the docs included an example config. 

For instance:
- How do I save the `html` resulting on an HTML file?
- How do I config the var `locals`? 

Thank you

**Comment by TimothyGu** [comment]
Welcome! pug-loader doesn't generate a HTML. Instead, its job is to compile the Pug template into a JavaScript function you can use client-side. locals is a render-time thing, but the loader generates a function that takes locals. You might have better luck with pug-html-loader or check the guide [here](https://github.com/pugjs/pug-loader/pull/27/files#diff-04c6e90faac2675aa89e2176d2eec7d8R12). If you use the latter, "jade" has to be changed to "pug" of course.
