### ISSUE TITLE
Change not triggered when included file is updated.

### ISSUE THREAD

**Issue by janwirth** [pugjs/pug-loader#48]
When an included pug file is changed, the compilation process is not triggered.
The problem does not occur when using import in the stylus-loader for example.

```
1. git clone https://github.com/FranzSkuffka/pug-html-loader-bug
2. npm i
3. npm run dev
4. change https://github.com/FranzSkuffka/pug-html-loader-bug/blob/master/src/yo.pug
5. ???
6. no profit
```

**Comment by TimothyGu** [comment]
Works fine here. Can you give a reduced example?

**Comment by TimothyGu** [comment]
Here's how I tested:

``` js
// main.js
require('./a.pug')
```

``` pug
//- a.pug
include b.pug
h1 yay
```

``` pug
//- b.pug
h3 yay
```

``` sh
webpack -w --module-bind pug=pug main.js out.js
```

After starting the command, I tested changing b.pug and a.pug, separately. Webpack automatically rebuilds in both cases.

---

I don't see pug-loader in the package.json in your repo, nor do I see pug. It might be a problem on your end.

**Comment by janwirth** [comment]
I think I forgot saving it on install. There must be something messing with the sourcemaps. Thank you for looking into this.

**Comment by schleumer** [comment]
I can relate to this, it's happening to me too. Included files does not trigger watcher.

**Comment by TimothyGu** [comment]
@schleumer, again, can you provide a test case?

**Comment by schleumer** [comment]
Sure, i'm preparing it!

**Comment by schleumer** [comment]
@TimothyGu you got me, ehe. Making a project from scratch i noticed that it's a problem of [`vue-loader`](https://github.com/vuejs/vue-loader). Sorry.

**Comment by acopalipsis** [comment]
I have updates only `index.pug` and includes file no.
