### ISSUE TITLE
Broken with npm 2

### ISSUE THREAD

**Issue by Akkuma** [pugjs/pug-loader#56]
`Module build failed: Error: Cannot find module 'pug-walk' from '/Users/removed/workspace/projectNameRemoved/node_modules/pug/lib'

This appears to happen on `modulePaths.walk = nodeResolve("pug-walk", {basedir: dirname(modulePaths.pug)});`

**Comment by TimothyGu** [comment]
I'll take a look. This is the same issue #49 is trying to fix.

**Comment by TimothyGu** [comment]
#49 has been merged.
