### ISSUE TITLE
Make variable accessible in all pug files

### ISSUE THREAD

**Issue by lekhnath** [pugjs/pug-loader#57]
Using this loader how can I make some vairable accessible to all pug/jade files. For example in express app I could do:

`app.locals.assetPath = path.resolve('public/assets');`

and the variable `assetPath` would be available in all jade files. But with webpack I am not able to do the same.

In my `webpack.config.js` I tried following but could not get work:

```
    {
      test: /.pug$/,
      loader: 'pug',
      query: {
        root: path.join(__dirname, 'src/app'),

        /*globals: {assetPath: '/hard/coded/value'}*/ //WILL NOT WORK

        /*locals: {assetPath: '/hard/coded/value'}*/ //WILL NOT WORK

        /*locals: {assetPath: '/hard/coded/value'}, globals: ['assetPath']*/ //WILL NOT WORK
      }
```

[Stackoverflow](http://stackoverflow.com/questions/38980925/make-variable-accessible-in-all-pug-files)

**Comment by TimothyGu** [comment]
This loader returns a template function for use on the client. It does not return rendered HTML. See [Usage](https://github.com/pugjs/pug-loader#usage) for more information.

**Comment by lekhnath** [comment]
Thats  why I choosed this module but how to make some variable accessible to all the jade/pug files like I used to do in express app is my real question. I was wondering if I could do something in `webpack.config.js`. I don't want to pass the same variable in all jade files instead I want to configure somewhere to provide local variables to all the jade files. Any clue on that?
Thanks.

**Comment by TimothyGu** [comment]
No, pug-loader doesn't touch locals _at all._

For Pug, there are two steps to the process of turning Pug into HTML: compiling, which turns Pug code into a JavaScript function, and rendering, which passes locals into the function to get an HTML string. Locals are only used in the second step. This module is only concerned with the first step.
