### ISSUE TITLE
Doesnot support legacy *.jade in include when ommiting extension

### ISSUE THREAD

**Issue by lekhnath** [pugjs/pug-loader#58]
extends ./layout //DOESNOT WORK

extends ./layout.jade //WORKS

**BUT** no problem with .pug

If I have layout2.pug then both of the following works

extends ./layout2

extends ./layout2.pug

**Comment by TimothyGu** [comment]
This is a Pug behavior, not specific to pug-loader, and to really fix this we need to do file system IO within the parser core, which is something I would like to prevent doing. If we do allow this, it also begs the question of which file to pick if both are present.
