### ISSUE TITLE
Cannot read property 'length' of undefined (of pug_obj0.length)

### ISSUE THREAD

**Issue by mxmaxime** [pugjs/pug-loader#63]
Hello, my problem :
I do :
`const template = require('../templates/home')`
But i have this error in the browser console :
`home.pug?46b2:10Uncaught TypeError: Cannot read property 'length' of undefined`
It's on : 
`if ('number' == typeof pug_obj0.length) [....]`

**Comment by CraigglesO** [comment]
You need to write, "require('../templates/home.pug)"
The Readme.md explains this.
