### ISSUE TITLE
Handle `extends` and `Includes` keywords

### ISSUE THREAD

**Issue by ColCh** [pugjs/pug-loader#7]
Is it possible to resolve 'em like CSS `@import` ones?

**Comment by sokra** [comment]
They are handled by this loader.

Can you give an example?

**Comment by ColCh** [comment]
Yes.

Please see [this runnable example](http://runnable.com/VBV0awUUA_AUt-CN/webpack-including-in-jade-loader-for-node-js-and-hello-world) (Click on **Run**) 
Layout is from [jade documentation on include](http://jade-lang.com/reference/includes/)

**Comment by ybian** [comment]
+1. Do we have any update on this? This looks like an important feature.

**Comment by nazimjamil** [comment]
Would be fantastic to see movement on this.

**Comment by davidnormo** [comment]
Agreed!

**Comment by JSteunou** [comment]
It works perfectly fine guys...

**Comment by TimothyGu** [comment]
Runnable is down and I don't think there are any Pug features the loader doesn't accept/support.
