### ISSUE TITLE
SyntaxError: Unexpected character '`'

### ISSUE THREAD

**Issue by notiv-nt** [pugjs/pug-loader#73]
Hello, i changed jade-loader to pug-loader, and my build doesn'to work now:

webpack config: http://pastebin.com/CWVx3v2S

Run:
```
./node_modules/.bin/webpack --progress --watch --inline -p --devtool
```

Code:
```
main.js:
var a = require('pug/timeline.pug')({
  table: 'table___3AgIg',
  date: 'date___2SiYk'
});


timeline.pug:
div(class=`${table} ${date}`)


Console:
ERROR in main.bundle.js from UglifyJs
SyntaxError: Unexpected character '`' [../~/pug-loader?{"pretty":true}!./pug/timeline.pug:4,0]
```

Tests:

```
YES:
  div(class=table)
    //- <div class="table___3AgIg"></div>

  div(class=table + ' ' + date)
    //- <div class="table___3AgIg date___2SiYk"></div>

  div(class=`${'str'}`)
    //- <div class="str"></div>

NO:
  div(class="#{table} #{date}")
    //- <div class="#{table} #{date}"></div>

  div(class='#{table} #{date}')
    //- <div class="#{table} #{date}"></div>

  div(class=`#{table} #{date}`)
    //- <div class="#{table} #{date}"></div>

  div(class="${table} ${date}")
    //- <div class="${table} ${date}"></div>

  div(class='${table} ${date}')
    //- <div class="${table} ${date}"></div>


ERROR: WHY ?????
  div(class=`${table} ${date}`)
    SyntaxError: Unexpected character '`' [../~/pug-loader?{"pretty":true}!./pug/timeline.pug:4,0]

```

---

And funny thing:
`node pug_test.js `:
```
var pug = require('pug');

var html = pug.renderFile('./src/pug/timeline.pug', {
	table: 'table___3AgIg',
	date: 'date___2SiYk'
});

console.dir(html);
```

Outputs:
```
'<div class="table___3AgIg date___2SiYk"></div>'
```

This problem occurs only when im using `-p` parameter http://webpack.github.io/docs/cli.html#production-shortcut-p

**Comment by JustinLivi** [comment]
@notiv-nt You can pipe pug-loader output to babel-loader:

```javascript
{
    test: /\.pug$/, loader: 'babel-loader?presets[]=es2015!pug',
}
```

**Comment by marxjb** [comment]
@JustinLivi would you mind elaborating why this is necessary? This isn't SO, but some additional information would probably be helpful to understand the underlying issue. Thank you very much

**Comment by JustinLivi** [comment]
Sure! You're right, I provided a workaround without really explaining the cause of the issue. The cause of the issue was the use of [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in the timeline.pug file:

```javascript
div(class=`${table} ${date}`)
```
The error actually was not generated by pug-loader at all, but by UglifyJS (which I assume was further down the build pipeline). As far as I know, Uglify does not support template literals. Piping through the babel loader transpiles the template literals into ES5 string concatenation, which UglifyJS supports. I wonder if perhaps jade-loader automatically performed this transpilation?

**Comment by marxjb** [comment]
I'm pretty sure at least the pug-loader does it automatically (now?), because I encountered the issue at hand only while building for production (including uglifyjs)

**Comment by JustinLivi** [comment]
It's also possible that the template strings were passed through untouched, but you were testing in browsers that support template literals? Support in modern browsers is pretty good now: https://caniuse.com/#feat=template I'm not sure what other differences exist between your development and production pipeline.

One other thing which might help people in the future, is the loader string I provided should be the following when using webpack@3:

```javascript
{
    test: /\.pug$/, loader: 'babel-loader?presets[]=es2015!pug-loader',
}
```

**Comment by marxjb** [comment]
I was testing in the latest chrome version. however, in production, it didn't work either, only after applying the fix you posted, piping it through babel (which we are also using)

**Comment by vviikk** [comment]
Hi! Late to the party, and yes, it was also UglifyJS that was causing the breakage as it did not understand string literals. I used the following configuration.

        loader: `babel-loader?presets[]=env!pug-loader`,

And use the new env way of doing things. This basically allowed us to use the same ESxx stuff we were using in the rest of the project. The problem isn't actually with Pug or the loader. I believe this should be done in Webpack / whatever build tool you're using.

And I also have the following plugins in my `.babelrc`:
```javascript
  "plugins": [
    "lodash",
    "transform-runtime",
    "transform-es2015-template-literals", // <- this transforms template literals
    "transform-decorators-legacy"
  ],
```
