### ISSUE TITLE
Pug semver 2.0.0-beta11 is lower than 2.0.0-beta6

### ISSUE THREAD

**Issue by pgilad** [pugjs/pug-loader#76]
This messes up the `peerDependency` validation of `>= 2.0.0-beta3` which `2.0.0-beta11` is not.

So the `peerDependency` here needs to be fixed (perhaps to something like `>=2.0.0-beta`)

**Comment by medialwerk** [comment]
Due to semver you have to write the perelease tags with a dot between "beta" and the number:
https://docs.npmjs.com/misc/semver#prerelease-tags
Could that lead to this issue?

**Comment by AckerApple** [comment]
Since I'm only converting pugs to static html, I'm going to try and switch away from pug-loader to pug-html-loader to avoid this distracting red in capitals "UNMET PEER DEPENDENCY".

Opinion, we don't need peerDependency checking for such a rather solid package.

**Comment by gs00s** [comment]
@TimothyGu What do you think, what would be the solution here? Enable all 2.* versions of pug?

**Comment by VitorLuizC** [comment]
This issue causes errors on c9.io environment.

**Comment by VitorLuizC** [comment]
Does #79 fixed this issue? Why this is not on the published(npm) pug-loader?

**Comment by neves** [comment]
Please, release a new version with that fix.

**Comment by VitorLuizC** [comment]
A way to solve it, until they publish the fixed one, is install from GitHub instead of NPM.
```sh
npm install pugjs/pug-loader
```

**Comment by johnathankent** [comment]
@blacksonic has the right idea. The zero-dots are unnecessary in this version. See https://github.com/npm/node-semver#advanced-range-syntax.

**Comment by TimothyGu** [comment]
Yeah… tweaking the version requirement is really the most we can do here. Can any of you confirm if #79 fixes this issue already or is #89 necessary too? I'll get a new release published when I can be sure this is resolved.

**Comment by gs00s** [comment]
With rc releases it works

**Comment by ForbesLindesay** [comment]
This has been fixed by much newer versions being released :)
