### ISSUE TITLE
webpack-dev-server fails on pug syntax error

### ISSUE THREAD

**Issue by vtlk2012** [pugjs/pug-loader#77]
I have webpack with my config. Everything is working as I expected. But when I trying to write my code with dev-server and pug-loader, something bad is going on. When pug has syntax error and throw exception, my dev-server is fails, and I must re-run it each time. 

**Issue**
In pug-loader (\node_modules\pug-loader\index.js) on string 155 we have `throw e`, and this is our problem, because pug loader do not return anything, just throw error. 

**Solution**
Just replace string 155 with `loaderContext.callback(e)`, and problem is gone. 

Here is shortlist of dependencies

```javascript
{
"pug": "^2.0.0-beta11",
"pug-loader": "^2.3.0",
"webpack": "^2.2.1",
"webpack-dev-server": "^2.3.0"
}
```

**Comment by Pinpickle** [comment]
I ran into this as well. I opened a PR #78
