### ISSUE TITLE
Pass data to pug files

### ISSUE THREAD

**Issue by bardaxx** [pugjs/pug-loader#92]
Hello, there is a way to pass data to pugs files?
eg:

```
data: {
  language: currentLang,
  global: require(`./src/content/global.json`),
  home: require(`./src/content/home.json`),
  about: require(`./src/content/about.json`),
}
```

Thank you so much!

**Comment by kugaevsky** [comment]
As I see `require('./template.pug')(data)`. Try it.

**Comment by bardaxx** [comment]
Solved with HtmlWebpackPlugin! Thank you ;)

**Comment by melv-n** [comment]
@giacomoalonzi How did you solve it? I'm also looking for a way to pass locals into Pug

**Comment by bardaxx** [comment]
@mirague check this https://github.com/jantimon/html-webpack-plugin/issues/747
